language: node_js
node_js:
  - '18'

cache:
  directories:
    - node_modules

branches:
  only:
    - main

install:
  - npm install
  - npm run build

script:
  - npm run test -- --watch=false --browsers=ChromeHeadless

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "soyangelcareaga@gmail.com"
  api_key: $NPM_API_KEY
  on:
    branch: main
  skip_cleanup: true

notifications:
  email:
    recipients:
      - soyangelcareaga@gmail.com
    on_success: change
    on_failure: always
